global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["local:9100"]

  - job_name: "filestat-exporter"
    static_configs:
      - targets: ["filestat-exporter:9943"]
