global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["local:9100"]

  - job_name: "filestat-exporter"
    static_configs:
      - targets: ["filestat-exporter:9943"]

  - job_name: "blackbox-exporter"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - "http://prometheus.io"
    # Write target into instance-label
    # See also: https://prometheus.io/docs/guides/multi-target-exporter/#querying-multi-target-exporters-with-prometheus
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'windows_exporter'
    static_configs:
      - targets: ["windows:9182"]
